name: pro
version: 0.0.0
description:  an experiment in cooperative computing
repository: https://github.com/lambdageek/pro-dart
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  async: ^2.4.0
  meta: ^1.1.8
dev_dependencies:
  pedantic: ^1.8.0
  effective_dart: ^1.2.0

    
